### ISSUE TITLE
wasapi vs mme

### ISSUE THREAD

**Issue by A-Kimpton** [intxcc/pyaudio_portaudio#14]
Hey,

Just wanted to say thanks, this worked perfectly. 

Just had a question about wasapi and mme:
I noticed a lot of my output devices were mme, and it looks like this port doesn't like loopback on mme api devices. Is this a bug? Or just a limitation?

If you run your sample script, if i select a mme output device it tells me its a input device (because it's not wasapi) and says its not supported.

**Comment by intxcc** [comment]
Hi @A-Kimpton !

Happy that everything is working for you :)

The thing is that this forked repo does make use of a specific WASAPI feature, called loopback mode. For reference go to this page: https://docs.microsoft.com/de-de/windows/desktop/CoreAudio/loopback-recording

> WASAPI provides loopback mode primarily to support acoustic echo cancellation (AEC). However, other types of audio applications might find loopback mode useful for capturing the system mix that is being played by the audio engine.

So only devices that support WASAPI can be used. But since WASAPI is merely a wrapper windows provides for a device that should include most devices.
