### ISSUE TITLE
Using with Python 3.5

### ISSUE THREAD

**Issue by ailgup** [intxcc/pyaudio_portaudio#2]
Has anyone been able to get this to work on Python 3.5 (Windows 64-bit)? I got it to compile with Cygwin however that currently only supports up to Python 3.4. On 3.5 when I run setup.py I get an error while building '_portaudio'.

**Comment by intxcc** [comment]
That is because this repository was made for cygwin. But I just rebuild everything with Visual Studio, to get a native Windows build. Here you go, have fun with it :)

Build with "python setup.py bdist_wininst --static-link" for Python 3.5 amd64 as a Standalone installer. I might upload the source code for that as well, but I will have to restructure the repo for seperated native/cygwin first.

[PyAudio-0.2.7.win-amd64-py3.5.zip](https://github.com/intxcc/pyaudio_portaudio/files/335822/PyAudio-0.2.7.win-amd64-py3.5.zip)
